version: '3.8'

services:
  vmr-cleanup:
    build: .
    dns:
      - 10.0.0.25
    volumes:
      - ./certs:/app/certs:ro  # Mount certs read-only
      - ./.env:/app/.env:ro  # Optional if you don't bake env vars into image
    env_file:
      - .env